---
postgresql_version: "14"
postgresql_listen_addresses: "*"
postgresql_port: 5432
postgresql_bin_dir: "/usr/pgsql-{{ postgresql_version }}/bin"
postgresql_data_dir: "/var/lib/pgsql/{{ postgresql_version }}/data"
postgresql_max_connections: 100
postgresql_global_params: {}
