---
postgresql_core_version: "14"
postgresql_core_listen_addresses: "*"
postgresql_core_port: 5432
postgresql_core_bin_dir: "/usr/pgsql-{{ postgresql_core_version }}/bin"
postgresql_core_data_dir: "/var/lib/pgsql/{{ postgresql_core_version }}/data"
postgresql_core_max_connections: 100
postgresql_core_global_params: {}
postgresql_core_user: postgres
postgresql_core_group: postgres
