---
# Zabbix API接続情報
zabbix_config_api_url: "http://localhost/zabbix"
zabbix_config_api_user: "Admin"
zabbix_config_api_password: "zabbix"  # Vault等での上書き前提

# 自動登録ルール (Auto Registration)
zabbix_config_autoreg_name: "Auto registration for Linux"
zabbix_config_autoreg_metadata: "Linux"
zabbix_config_autoreg_group: "Linux servers"
zabbix_config_autoreg_template: "Linux by Zabbix agent"

# API接続タイムアウト設定
zabbix_config_api_timeout: 30
zabbix_config_api_validate_certs: false
