---
- name: Import install tasks
  ansible.builtin.import_tasks:
    file: 01_install.yml

- name: Import initialize tasks
  ansible.builtin.import_tasks:
    file: 02_initialize.yml

- name: Import service tasks
  ansible.builtin.import_tasks:
    file: 03_service.yml
