---
# テスト用変数
zabbix_server_core_db_name: "zabbix"
zabbix_server_core_db_user: "zabbix"
zabbix_server_core_db_password: "password_for_test"

# Zabbix API設定
zabbix_api_url: "http://localhost/zabbix"
zabbix_api_user: "Admin"
zabbix_api_password: "zabbix"

# 自動登録ルールのテスト設定
zabbix_autoreg_name: "Auto registration for Linux"
zabbix_autoreg_metadata: "Linux"
zabbix_autoreg_group: "Linux servers"
zabbix_autoreg_template: "Linux by Zabbix agent"

# テストはコンテナ環境で実施
is_container_env: true
