---
- name: Create setenv.d directory
  ansible.builtin.file:
    path: "{{ tomcat_install_dir }}/bin/setenv.d"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0750'

- name: Configure setenv.sh
  ansible.builtin.template:
    src: setenv.sh.j2
    dest: "{{ tomcat_install_dir }}/bin/setenv.sh"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0750'
  notify: Restart Tomcat
