---
- name: Include install tasks
  ansible.builtin.include_tasks: 01_install.yml

- name: Include configure tasks
  ansible.builtin.include_tasks: 02_configure.yml

- name: Include create setenv tasks
  ansible.builtin.include_tasks: 03_create_setenv.yml
