---
# vars/Windows.yml

# Service & Paths
zabbix_agent_core_service_name: "Zabbix Agent 2"
zabbix_agent_core_config_file: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.conf'
zabbix_agent_core_log_file: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.log'
# Windows版Agent2もInclude設定は可能
zabbix_agent_core_include_dir: 'C:\Program Files\Zabbix Agent 2\zabbix_agent2.d'

# Installer Settings
_win_base_url: "https://cdn.zabbix.com/zabbix/binaries/stable/{{ zabbix_agent_core_version }}/{{ zabbix_agent_core_windows_version }}"
zabbix_agent_core_windows_installer_url: "{{ _win_base_url }}/zabbix_agent2-{{ zabbix_agent_core_windows_version }}-windows-amd64-openssl.msi"
zabbix_agent_core_windows_installer_path: 'C:\Windows\Temp\zabbix_agent2.msi'
