galaxy_info:
  author: your company
  description: WSUS Server Core Role
  company: your company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2016
        - 2019
        - 2022
  galaxy_tags:
    - windows
    - wsus
    - update

dependencies: []
