---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Include zabbix_agent_core role
      ansible.builtin.include_role:
        name: "middleware.middleware.zabbix_agent_core"

    - name: Dump role variables to JSON for Testinfra
      ansible.builtin.include_role:
        name: "middleware.middleware.zabbix_agent_core"
        tasks_from: tests/dump_vars.yml
