---
galaxy_info:
  author: HyperGenius
  description: Zabbix Configuration Role (API-based configuration)
  company: HyperGenius
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions: ['8', '9']
  galaxy_tags:
    - zabbix
    - monitoring
    - configuration

dependencies: []
