---
# Zabbixエージェント2のインストール (RHEL系)
- name: Install Zabbix Agent 2
  ansible.builtin.dnf:
    name:
      - zabbix-agent2
    state: present
  when: ansible_os_family == "RedHat"

# TODO: 他のLinuxディストリビューションのサポートを追加
