---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Include core role"
      include_role:
        name: "middleware.middleware.nginx_core"

    - name: Dump variables
      include_role:
        name: "middleware.middleware.nginx_core"
        tasks_from: tests/dump_vars.yml
