galaxy_info:
  author: HyperGenius
  description: PostgreSQL Core Role
  company: HyperGenius
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - postgresql
    - database

dependencies: []
