---
full_nginx_version: "2:1.20.1-24"
nginx_http_port: 80
nginx_user: nginx
nginx_worker_processes: "auto"
nginx_server_tokens: "off"
nginx_client_max_body_size: "1m"
nginx_keepalive_timeout: "65"
nginx_global_params: {}
