---
# Zabbixエージェント2のファイアウォール設定 (Windows)
- name: Allow Zabbix Agent port through Windows Firewall
  community.windows.win_firewall_rule:
    name: "Zabbix Agent 2"
    localport: "{{ zabbix_agent_core_listen_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: true
  when: zabbix_agent_core_configure_firewall | bool
