---
tomcat_core_service_name: tomcat
tomcat_core_catalina_home: /usr/share/tomcat
tomcat_core_install_dir: /opt/tomcat
tomcat_core_conf_dir: /opt/tomcat/conf
tomcat_core_bin_dir: /usr/share/tomcat/bin
